language: c
before_install:
    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get install binutils make python3 python3-dev
    - sudo curl http://python-distribute.org/distribute_setup.py | sudo python3
    - sudo curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python3
    - sudo pip install pytest
script:
    - python3 setup.py install
    - cd tests
    - py.test .
