language: c
before_install:
    - sudo apt-get install binutils make python3
script:
    - curl http://python-distribute.org/distribute_setup.py | sudo python3
    - curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python3
    - pip install pytest
    - python3 setup.py build
    - cd tests
    - py.test .
